const staticData = [
    {
        'sector_name': 'CSS',
        'sector_account': 'J8aYFqhRnMmT5MUJg6JhBFUWJMty7VRTMZMpsJA56ttG',
        'planet_account': 'FrsvtcB3qLBHAj8L451nbTwg29xU7j1zcYEF9muJnrTx',
        'resource_account': 'HYDR4EPHJcDPcaLYUcNCtrXUdt1PnaN4MvE655pevBYp',
        'resource_name': 'Hydrogen',
    },
    {
        'sector_name': 'UST2',
        'sector_account': 'GRTYCZ5vCtV71rNt1Y1NsXsCpD5x1AGoNZrbbZe3nw8N',
        'planet_account': 'CJWNinTSHY92KsYkiBNoWjrs5xsZWNJ4hUgAzAHvDWpj',
        'resource_account': 'MASS9GqtJz6ABisAxcUn3FeR4phMqH1XfG6LPKJePog',
        'resource_name': 'Biomass',
    },
    {
        'sector_name': 'UST3',
        'sector_account': 'F9uCoY8mLhG5hURQ1aVMy9YPaaeFDvsjvRAw5b55GfzS',
        'planet_account': 'B4o6peamQyromtiWPVPiicWu8SWkNvyC6s6XuT8umLiz',
        'resource_account': 'CARBWKWvxEuMcq3MqCxYfi7UoFVpL9c4rsQS99tw6i4X',
        'resource_name': 'Carbon',
    },
    {
        'sector_name': 'UST4',
        'sector_account': 'EmZPZuUmHx8hvwqaiscVkt88GLDviDvbQDaZgBSsk3eg',
        'planet_account': '22oUsXjN6Vz895qKmS5sDfshTpPWTFhozoQjGBQXozDL',
        'resource_account': 'FeorejFjRRAfusN9Fg3WjEZ1dRCf74o6xwT5vDt3R34J',
        'resource_name': 'Iron ore',
    },
    {
        'sector_name': 'UST5',
        'sector_account': '8KysVHzj1spsR5kQZgy4N5iu9NGxcWWMdsfvEXvRmQtz',
        'planet_account': 'EbcNwRXwLAQDFiiTvW1oppCWrrXFUBPGSnUNSFSXyg7n',
        'resource_account': 'CUore1tNkiubxSwDEtLc3Ybs1xfWLs8uGjyydUYZ25xc',
        'resource_name': 'Copper ore',
    },
    {
        'sector_name': 'MRZ35',
        'sector_account': 'C7vNHtrsogkHohNd97HAY96uHKxRi6qMEupJ1779hnmU',
        'planet_account': '8rYh2TZW8RCX1NV72NtjHUgKn49XMDuBnVCwyoiaurDF',
        'resource_account': 'CUore1tNkiubxSwDEtLc3Ybs1xfWLs8uGjyydUYZ25xc',
        'resource_name': 'Copper ore',
    },
    {
        'sector_name': 'MRZ35',
        'sector_account': 'C7vNHtrsogkHohNd97HAY96uHKxRi6qMEupJ1779hnmU',
        'planet_account': '8rYh2TZW8RCX1NV72NtjHUgKn49XMDuBnVCwyoiaurDF',
        'resource_account': 'FeorejFjRRAfusN9Fg3WjEZ1dRCf74o6xwT5vDt3R34J',
        'resource_name': 'Iron ore',
    },
    {
        'sector_name': 'MRZ22',
        'sector_account': 'GFJbujH4Y9Rg7u9T9SsLRwQtHD91dLfVNmhqF2bFZeg5',
        'planet_account': '9JSDc6VE7Yza2YB7XAMeCYvwph1p16mvbhrfb3KPEpXV',
        'resource_account': 'LUMACqD5LaKjs1AeuJYToybasTXoYQ7YkxJEc4jowNj',
        'resource_name': 'Lumanite',
    },
    {
        'sector_name': 'MRZ23',
        'sector_account': '6jxZZsNZMuMQ3ypnFFe1yRYGshhNmPRtnafk3yFxanyK',
        'planet_account': 'DKQuMZN2KUwc3NVsg4gLFtkeLRGxTQtu2FCoXgaXerQn',
        'resource_account': 'MASS9GqtJz6ABisAxcUn3FeR4phMqH1XfG6LPKJePog',
        'resource_name': 'Biomass',
    },
    {
        'sector_name': 'MRZ23',
        'sector_account': '6jxZZsNZMuMQ3ypnFFe1yRYGshhNmPRtnafk3yFxanyK',
        'planet_account': 'DKQuMZN2KUwc3NVsg4gLFtkeLRGxTQtu2FCoXgaXerQn',
        'resource_account': 'FeorejFjRRAfusN9Fg3WjEZ1dRCf74o6xwT5vDt3R34J',
        'resource_name': 'Iron ore',
    },
    {
        'sector_name': 'MRZ16',
        'sector_account': '9Vpcu9bheTFBevaJeJJrvSw38wnC4PuzawiBHpQZAVnn',
        'planet_account': '5GprHuuwmUMSMvp4r1WV9DkmMqjBVcqSnjYvzQw8HhbL',
        'resource_account': 'FeorejFjRRAfusN9Fg3WjEZ1dRCf74o6xwT5vDt3R34J',
        'resource_name': 'Iron ore',
    },
    {
        'sector_name': 'MRZ15',
        'sector_account': 'GNeJCnCYMCnftuPzJcX8hMoa1uvGhq6wdoXGKiZNbdaP',
        'planet_account': 'FWpvY4paPtXEdZgSxTbiJV3nHPvAmneoF4xaQis1hQ1H',
        'resource_account': 'HYDR4EPHJcDPcaLYUcNCtrXUdt1PnaN4MvE655pevBYp',
        'resource_name': 'Hydrogen',
    },
    {
        'sector_name': 'MRZ15',
        'sector_account': 'GNeJCnCYMCnftuPzJcX8hMoa1uvGhq6wdoXGKiZNbdaP',
        'planet_account': 'FWpvY4paPtXEdZgSxTbiJV3nHPvAmneoF4xaQis1hQ1H',
        'resource_account': 'CUore1tNkiubxSwDEtLc3Ybs1xfWLs8uGjyydUYZ25xc',
        'resource_name': 'Copper ore',
    },
    {
        'sector_name': 'MRZ21',
        'sector_account': '6Qtc1jHHpiAFCPVTWzYzUQpts96u9tfsXwjxNy9xL6Cf',
        'planet_account': 'JCAmcdThHeLJrFY8sHgqGGdsYwxUSD9ZPXwhLGst7rbn',
        'resource_account': 'HYDR4EPHJcDPcaLYUcNCtrXUdt1PnaN4MvE655pevBYp',
        'resource_name': 'Hydrogen',
    },
    {
        'sector_name': 'MRZ28',
        'sector_account': 'ESDHL8fHMUjJXnwZqt4JbqjWgpKZnJf994Nr8EPEtpU5',
        'planet_account': '8v6Y9gkbX15h2Dys8zuUmFaFKWySfrtjXdUUC8CXK6XK',
        'resource_account': 'HYDR4EPHJcDPcaLYUcNCtrXUdt1PnaN4MvE655pevBYp',
        'resource_name': 'Hydrogen',
    },
    {
        'sector_name': 'MRZ28',
        'sector_account': 'ESDHL8fHMUjJXnwZqt4JbqjWgpKZnJf994Nr8EPEtpU5',
        'planet_account': '8v6Y9gkbX15h2Dys8zuUmFaFKWySfrtjXdUUC8CXK6XK',
        'resource_account': 'CARBWKWvxEuMcq3MqCxYfi7UoFVpL9c4rsQS99tw6i4X',
        'resource_name': 'Carbon',
    },
    {
        'sector_name': 'MRZ34',
        'sector_account': 'ByfEohDQG4ZjjD6xwy8EFkABREr3wdaHgqNyyhrHwyLT',
        'planet_account': 'ErCLGw3vUd88vxQQ4GPjLQFTJDWwaFywPx6ZA2Eufqyp',
        'resource_account': 'CARBWKWvxEuMcq3MqCxYfi7UoFVpL9c4rsQS99tw6i4X',
        'resource_name': 'Carbon',
    },
    {
        'sector_name': 'MRZ34',
        'sector_account': 'ByfEohDQG4ZjjD6xwy8EFkABREr3wdaHgqNyyhrHwyLT',
        'planet_account': 'ErCLGw3vUd88vxQQ4GPjLQFTJDWwaFywPx6ZA2Eufqyp',
        'resource_account': 'CUore1tNkiubxSwDEtLc3Ybs1xfWLs8uGjyydUYZ25xc',
        'resource_name': 'Copper ore',
    },
    {
        'sector_name': 'MRZ33',
        'sector_account': 'SiURsYQ61UoasqjWip3eXpKB59RovwX4DmCtvFWaGHC',
        'planet_account': 'EPexHvKhnpWhee4Gb6Se64qq6URFB6xZm9JFFvSJEo4D',
        'resource_account': 'CARBWKWvxEuMcq3MqCxYfi7UoFVpL9c4rsQS99tw6i4X',
        'resource_name': 'Carbon',
    },
    {
        'sector_name': 'MRZ33',
        'sector_account': 'SiURsYQ61UoasqjWip3eXpKB59RovwX4DmCtvFWaGHC',
        'planet_account': 'EPexHvKhnpWhee4Gb6Se64qq6URFB6xZm9JFFvSJEo4D',
        'resource_account': 'MASS9GqtJz6ABisAxcUn3FeR4phMqH1XfG6LPKJePog',
        'resource_name': 'Biomass',
    },
    {
        'sector_name': 'MRZ32',
        'sector_account': 'EyBWLPS4HJTkbV6XRYoZiedsSm5zNs6A3dwmaQcjJ2S4',
        'planet_account': 'BhpPLg51VZEtBvSYJXx7SbaZsd9HdHJAPQMojCpTvhFD',
        'resource_account': 'CARBWKWvxEuMcq3MqCxYfi7UoFVpL9c4rsQS99tw6i4X',
        'resource_name': 'Carbon',
    },
    {
        'sector_name': 'MRZ17',
        'sector_account': '7f3z7FTzmQwQ3zBLgxXA95yjm36BcKX44UtTGNgcDT2S',
        'planet_account': '2j978r1yoSa1eS7vojjRjhARCie2EThLeUP1hfSXnYma',
        'resource_account': 'ARCoQ9dndpg6wE2rRexzfwgJR3NoWWhpcww3xQcQLukg',
        'resource_name': 'Arco',
    },
    {
        'sector_name': 'MRZ27',
        'sector_account': '24qmWfZssmNPH7vT2GViqXbSEh8yuVGrnzRdFYjh5Tho',
        'planet_account': 'GTS9gBsuRRSZwGSJAwLY6iJH5LyvEmNSxBXfns6wNnAF',
        'resource_account': 'LUMACqD5LaKjs1AeuJYToybasTXoYQ7YkxJEc4jowNj',
        'resource_name': 'Lumanite',
    }
];

export default staticData;